# Generated by Django 5.0.7 on 2024-07-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_socials_portfolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socials',
            options={'verbose_name_plural': 'Socials'},
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume'),
        ),
    ]
