# Generated by Django 5.0.7 on 2024-07-23 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_socials_options_alter_portfolio_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='website',
            new_name='github',
        ),
    ]
