# Generated by Django 5.0.7 on 2024-07-31 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_project_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='portfolio',
        ),
    ]
