# Generated by Django 5.0.7 on 2024-08-01 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_project_options_project_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socials',
            name='portfolio',
        ),
    ]
